; PlatformIO Project Configuration File

[platformio]
default_envs = esp32dev-bt-radio

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps =
    esphome/ESP32-audioI2S

[env:esp32dev-bt-radio]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
board_build.psram = enabled
build_flags =
    -DA2DP_LEGACY_I2S_SUPPORT=1
    -DA2DP_I2S_AUDIOTOOLS=0
    -DBT_MODE_CLASSIC_BT=ESP_BT_MODE_CLASSIC_BT
    -DBT_MODE_BLE=ESP_BT_MODE_BLE
    -DBT_MODE_BTDM=ESP_BT_MODE_BTDM
    -D"btStartMode(x)=btStart()"
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -mfix-esp32-psram-cache-strategy=memw
lib_deps =
    esphome/ESP32-audioI2S
    https://github.com/pschatzmann/ESP32-A2DP
