; PlatformIO Project Configuration File

[platformio]
default_envs = esp32dev-bt-radio

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps =
    esphome/ESP32-audioI2S

[env:esp32dev-bt-radio]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
board_build.psram = enabled
build_flags =
    -DA2DP_LEGACY_I2S_SUPPORT=1
    -DA2DP_I2S_AUDIOTOOLS=0
    -DBT_MODE_CLASSIC_BT=ESP_BT_MODE_CLASSIC_BT
    -DBT_MODE_BLE=ESP_BT_MODE_BLE
    -DBT_MODE_BTDM=ESP_BT_MODE_BTDM
    -D"btStartMode(x)=btStart()"
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -mfix-esp32-psram-cache-strategy=memw
    -DUSER_SETUP_LOADED=1
    -DILI9488_DRIVER=1
    -DTFT_WIDTH=320
    -DTFT_HEIGHT=480
    -DTFT_MISO=19
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=5
    -DTFT_DC=27
    -DTFT_RST=33
    -DTOUCH_CS=-1
    -DTFT_RGB_ORDER=TFT_RGB
    -DTFT_INVERSION_ON
    -DSPI_FREQUENCY=8000000
    -DSPI_READ_FREQUENCY=2000000
    -DSUPPORT_TRANSACTIONS
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
lib_deps =
    esphome/ESP32-audioI2S
    https://github.com/pschatzmann/ESP32-A2DP
    bodmer/TFT_eSPI
    adafruit/Adafruit FT6206 Library
    bblanchon/ArduinoJson


